-- Initialize PostgreSQL database for Vulnerability Scanner

-- Create schema (optional, comment if not needed)
-- CREATE SCHEMA IF NOT EXISTS vuln_scanner;

-- Create extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Create tables (these will be auto-generated by Hibernate, but you can pre-create if needed)
-- Tables will be created automatically by Spring Data JPA with ddl-auto=update

-- Create indexes for better performance (optional)
CREATE INDEX IF NOT EXISTS idx_user_email ON user_info(email);
CREATE INDEX IF NOT EXISTS idx_scan_status ON abstract_scan(scan_status);
CREATE INDEX IF NOT EXISTS idx_scan_type ON abstract_scan(scan_type);
CREATE INDEX IF NOT EXISTS idx_scan_user_id ON abstract_scan(user_id);

-- Grant permissions (if using a separate user for the application)
-- GRANT ALL PRIVILEGES ON DATABASE vuln_scanner TO postgres;
