spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5433/vuln_scanner
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

# Multipart configuration
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

server.port=8081

# IA Engine
sast.engine.url=${SAST_ENGINE_URL:http://localhost:8000/api/v1/analyze}

# MobSF
mobsf.url=${MOBSF_URL:http://localhost:8008}
mobsf.api.key=${MOBSF_API_KEY:18d824c8c37ad0909e77da02c5950b41d06937cef5190518c0ebcc0ffa791104}
mobsf.connect-timeout=30
mobsf.read-timeout=600
mobsf.upload-dir=${UPLOAD_DIR:./uploads}
